# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/18b5a25c-0f56-4459-86bf-34a479b660b5";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/5a04b7f4-16e3-4ea2-b35d-2e389e1cae5c";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/18b5a25c-0f56-4459-86bf-34a479b660b5";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CDFD-93BA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/drives/2TB-M2" =
    { device = "/dev/disk/by-uuid/93a8adb9-ce25-4968-9ee4-57908e062b3d";
      fsType = "ext4";
    };

  fileSystems."/drives/4TB-M2" =
    { device = "/dev/disk/by-uuid/0cf48a8c-dcde-4281-bdbc-e0369cbe8782";
      fsType = "ext4";
    };

  fileSystems."/drives/1TB-HDD" =
    { device = "/dev/disk/by-uuid/432cd068-d54d-403a-b37c-43f255ff31c2";
      fsType = "ext4";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
