 { config, pkgs, ... }:
 {environment.systemPackages = with pkgs; [
    alacritty
    brave
    discord
    obs-studio
    steam
    helvum
    pavucontrol
    spotify
    git
    gnome.gnome-shell-extensions
    gnome-tweaks
    gnomeExtensions.arc-menu
    htop
    libreoffice-fresh
    linuxKernel.packages.linux_6_6.v4l2loopback
    nautilus-open-any-terminal
    neofetch
    git
    vim
    wget
    p7zip
    wine64Packages.stagingFull
    winePackages.stagingFull
    proton-caller
    protonup
    lutris
    ventoy
    prismlauncher
    kicad-unstable
    github-desktop
    xivlauncher
    vscode-with-extensions
    gimp
    davinci-resolve
    audacity
  ];}

